excludes:
  - \.git/.*
  - \.gitignore
  - .*lock
  - node_modules/.*
  - \.build/.*
  - src/_build/.*
  - scratch/.*
  - tools/.*
  - README.*
  - LICENSE.*
  - .*\.(md|rst|txt|xml|pot|po|json|yml|yaml|png|jpg|jpeg|gif|svg|ico|webp)
  - Makefile
  - eslint\.config\.js
  - .*\.(sh|py|css)
  - meson\.build
  - LINGUAS

licenses:
  - files: (src/.*\.ts|build\.js)$
    ident: GPL-3.0-or-later
    authors:
      - name: Jeff Shee
        email: jeffshee8969@gmail.com
    template: |
      Copyright (C) [year] [name of author] and contributors

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.

      You should have received a copy of the GNU General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

      SPDX-License-Identifier: [ident]
    unwrap_text: false

comments:
  - extensions:
      - js
      - ts
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
